import type { Metadata } from 'next'
import { DataContextProvider } from '@/contexts/data-context'
import { Inter } from 'next/font/google'
import './globals.css'
import { autoType, csvParse } from 'd3'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const predictionUrl = "http://localhost:8000/data/predictions.csv"
const testSetUrl = "http://localhost:8000/data/test_set.csv"

const fetchCSV = async (url: string) => {
  const resp = await fetch(url);
  const textData = await resp.text();
  return await csvParse(textData, autoType);
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const predictionData = await fetchCSV(predictionUrl)
  const testSetData = await fetchCSV(testSetUrl)
  // const filter_var: string = "number_of_rooms"
  
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <h1 id="title">Neufert 4.0 dashboard</h1>
        <div className="grid">
          <div id="sidebar">
            <nav>
              <ul>
                <li>
                  <Link href={"./parallel"}>Parallel</Link>
                </li>
                <li>
                  <Link href={"./prediction"}>Prediction</Link>
                </li>
              </ul>
            </nav>
        </div>
        <div id="main-container">
          <DataContextProvider predictionData={predictionData} testSetData={testSetData}>
            {children}
          </DataContextProvider>
          </div>
        </div>        
      </body>
    </html>
  )
}
